### ISSUE TITLE
Fastboot for Raspberry Pi 0 W

### ISSUE THREAD

**Issue by T94T** [furkantokac/buildroot#11]
What do I have to change if I want to compile your buildroot settings for a Raspberry Pi 0 W?
Including:
- WIFI network
- init system
- eudev
- USB support

Thanks a lot!

**Comment by furkantokac** [comment]
**Step 1**

Modify the ftdev_rpi3_fastboot_config for yourself, build it and run it without any problem on your RPI0W. You can get help from here https://furkantokac.com/rpi3-fast-boot-less-than-2-seconds/ and from @IronOxidizer 's repository: https://github.com/IronOxidizer/instant-pi He is working on RPI0W. If you've problem, I can create a script that creates image for your RPI0W

**Step 2**

Add the extras you want. For init system, Busybox Init should be enough for the most of the time. You should configure your kernel (`make linux-xconfig`) and packages (`make xconfig`) to have the supports of the features you want.

If you have a specific problem, please comment.
