### ISSUE TITLE
How to enable uart for debugging on usb (usb-ttl)

### ISSUE THREAD

**Issue by furkantokac** [furkantokac/buildroot#14]
## Enable UART

* Put `8250.nr_uarts=1` to cmdline.txt in boot partition.

## Redirect console to ttyAMA0

1. Go to /etc/inittab
2. Change the line `console::respawn:/sbin/getty -L  console 0 vt100 # GENERIC_SERIAL`
  to `ttyAMA0::respawn:/sbin/getty -L  ttyAMA0 0 vt100 # GENERIC_SERIAL`
  
  If you have problem, try `ttyS0` instead of `ttyAMA0`.

## Physical connection

1. Get your 3.3v usb-ttl hardware.
  ![image](https://user-images.githubusercontent.com/10312487/102382344-692ee200-3fdb-11eb-8b7c-575b781e2fd0.png)
2. USBTTL-TX to RPI-RX which is pin10 (GPIO15)
  USBTTL-RX to RPI-TX which is pin8 (GPIO14)
  USBTTL-GND to RPI-Ground which is pin6 (Ground)
  ![image](https://user-images.githubusercontent.com/10312487/102382507-94193600-3fdb-11eb-9613-36415cc90a1c.png)

**Comment by michal-lecki** [comment]
Hello @furkantokac.
I am trying to enable console access as you described above, but I am still getting only this output on UART:
`
Starting syslogd: OK
Starting klogd: OK
Initializing random number generator... done.
QIconvCodec::convertToUnicode: using Latin-1 for conversion, iconv_open failed
QIconvCodec::convertFromUnicode: using Latin-1 for conversion, iconv_open failed
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QFbVtHandler: socketpair() failed (Function not implemented)
Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).
libpng warning: iCCP: known incorrect sRGB profile
`

**Comment by furkantokac** [comment]
@michal-lecki You've successfully done it, just app is blocking the terminal login. Just go to `/etc/init.d/s12ftdev` and comment everything in it, or start the app in background by adding `&` the the end of the line of the app starting command.

**Comment by michal-lecki** [comment]
@furkantokac  Thank you for fast response. It helped, but I also had a typo in /etc/inittab which took me some time.

Works like a charm now.
