### ISSUE TITLE
Can i Run this script on armbian os and orange pi +2E?

### ISSUE THREAD

**Issue by EmadDeve20** [furkantokac/buildroot#34]
Hi. I developed a skid loader and I have to use this script to run!
And I have to use a USB flash drive for the user! Because a user may want to listen to music.
Anyway!

and after this command: ```make -h8``` I got Error with this message: ``` You must install `python` on your build machine```!

I think I can solve this error by creating an alias in bashrc file like This:
```alias python="python3"```

but this does not work!
how can I fix it?

python path in script just for rasbian os on rasbery pi 3 right?
and I must changing my python path in script to my python path! i right?

**Comment by ltorsini** [comment]
Same issue: "You must install `python` on your build machine"

Is there a fix?

**Comment by EmadDeve20** [comment]
Hello @ltorsini I can't remember why I open this issue!
I'm so sorry :)
Because I Work on a lot of projects and when I opened this issue,
I worked on a project like your repo. and past
for this I can't remember why I open this issue.
