### ISSUE TITLE
Professional and paid help needed! How to activate rpi camera and usb camera?

### ISSUE THREAD

**Issue by bunver** [furkantokac/buildroot#35]
Thanks for the great work!
I have a scenario that I need to fast boot and record 5-seconds of video clip from an rpi camera module or a usb camera and save it to the sd card. 
I appreciate if @furkantokac or anyone can help on this issue. 
I'm also open for getting professional paid support if someone has experience and interested in.
Thanks!

**Comment by furkantokac** [comment]
Lets talk on PM 👍
