### ISSUE TITLE
Have you considered providing ready to flash images?

### ISSUE THREAD

**Issue by guysoft** [furkantokac/buildroot#36]
Hey,
I was wondering if you would like any help making ready-to-flash images.

I also have a fork of [rpi-imager](https://github.com/guysoft/pi-imager) so it could all be point-click-flash.

**Comment by furkantokac** [comment]
Did you check the releases: https://github.com/furkantokac/buildroot/releases
It may be what you're looking for.

**Comment by guysoft** [comment]
Ok! Missed that!
